<?php
function warmshowers_site_enable() {
  update_sql("UPDATE {system} SET weight = 20 WHERE name = 'warmshowers_site'");
  update_sql("UPDATE {system} SET weight = 30 WHERE name = 'htmlmail'");
}

/**
 * Implementation of hook_update().
 */
function warmshowers_site_update_6001() {
  $ret = array();
  $ret[] = update_sql("UPDATE {system} SET weight = 20 WHERE name = 'warmshowers_site'");
  return $ret;
}

/**
 * htmlmail must run *after* this module so that we can alter
 * the mail before it gets turned into html mail.
 * If htmlmail is not already enabled, this will have to be done
 * manually.
 *
 * Apparently htmlmail reset its weight to 1 somewhere along the way, so trying again.
 */
function warmshowers_site_update_6003() {
  $ret = array();
  $ret[] = update_sql("UPDATE {system} SET weight = 30 WHERE name = 'htmlmail'");
  return $ret;
}
